'use strict';
const $=id=>document.getElementById(id), canvas=$('canvas'), ctx=canvas.getContext('2d');
let image=null, items=[], selected=-1, tool='select', zoom=1, drag=null, history=['[]'], historyIndex=0, toastTimer, filename='教學截圖';
const hints={select:'點選標註後拖曳移動；拖曳右下角控制點調整大小。',rect:'在圖片上按住拖曳，框出要強調的區域。',arrow:'從起點拖曳到目標，畫出指示箭頭。',number:'點一下圖片放置編號；編號會自動遞增。',text:'在左側輸入說明，再點一下圖片放置文字。',mosaic:'拖曳框選要遮蔽的區域。匯出前請確認遮蔽效果。'};
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500)}
function snapshot(){return JSON.stringify(items)}
function commit(){const state=snapshot();if(history[historyIndex]!==state){history=history.slice(0,historyIndex+1);history.push(state);if(history.length>80)history.shift();historyIndex=history.length-1}update();render()}
function undo(){if(historyIndex>0){items=JSON.parse(history[--historyIndex]);selected=-1;update();render()}}
function redo(){if(historyIndex<history.length-1){items=JSON.parse(history[++historyIndex]);selected=-1;update();render()}}
function update(){const ready=!!image;for(const id of ['export','fit','zoomIn','zoomOut'])$(id).disabled=!ready;$('undo').disabled=historyIndex===0;$('redo').disabled=historyIndex===history.length-1;$('delete').disabled=selected<0;$('count').textContent=items.length+' 個標註';$('settingsTitle').textContent=selected<0?'標註樣式':'選取標註的樣式';$('widthValue').value=$('width').value+' px';$('sizeValue').value=$('size').value+' px';$('zoomLabel').textContent=Math.round(zoom*100)+'%'}
function setTool(value){tool=value;selected=-1;document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===tool);b.setAttribute('aria-pressed',String(b.dataset.tool===tool))});$('hint').textContent=hints[tool];canvas.style.cursor=tool==='select'?'default':'crosshair';update();render()}
function bounds(o){if(o.type==='text'){ctx.font=`600 ${o.size}px "Microsoft JhengHei",sans-serif`;return{x:o.x,y:o.y,w:Math.max(10,...o.text.split('\n').map(t=>ctx.measureText(t).width)),h:o.text.split('\n').length*o.size*1.3}}if(o.type==='number')return{x:o.x-o.size*.68,y:o.y-o.size*.68,w:o.size*1.36,h:o.size*1.36};return{x:Math.min(o.x,o.x+o.w),y:Math.min(o.y,o.y+o.h),w:Math.abs(o.w),h:Math.abs(o.h)}}
function drawObject(c,o){c.save();c.strokeStyle=o.color;c.fillStyle=o.color;c.lineWidth=o.width;c.lineJoin='round';c.lineCap='round';if(o.type==='rect'){const b=bounds(o);c.strokeRect(b.x,b.y,b.w,b.h)}if(o.type==='arrow'){const ex=o.x+o.w,ey=o.y+o.h,a=Math.atan2(o.h,o.w),len=Math.min(Math.hypot(o.w,o.h)*.45,Math.max(18,o.width*3.5));c.beginPath();c.moveTo(o.x,o.y);c.lineTo(ex,ey);c.stroke();c.beginPath();c.moveTo(ex-len*Math.cos(a-.48),ey-len*Math.sin(a-.48));c.lineTo(ex,ey);c.lineTo(ex-len*Math.cos(a+.48),ey-len*Math.sin(a+.48));c.stroke()}if(o.type==='text'){c.font=`600 ${o.size}px "Microsoft JhengHei",sans-serif`;c.textBaseline='top';o.text.split('\n').forEach((line,i)=>c.fillText(line,o.x,o.y+i*o.size*1.3))}if(o.type==='number'){c.beginPath();c.arc(o.x,o.y,o.size*.68,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.font=`700 ${o.size*(String(o.n).length>2?.66:.9)}px sans-serif`;c.textAlign='center';c.textBaseline='middle';c.fillText(o.n,o.x,o.y+o.size*.03)}if(o.type==='mosaic'){const b=bounds(o),x=Math.max(0,Math.floor(b.x)),y=Math.max(0,Math.floor(b.y)),w=Math.min(image.width-x,Math.ceil(b.w)),h=Math.min(image.height-y,Math.ceil(b.h));if(w>0&&h>0){const tile=document.createElement('canvas');tile.width=Math.max(1,Math.ceil(w/18));tile.height=Math.max(1,Math.ceil(h/18));const tc=tile.getContext('2d');tc.drawImage(image,x,y,w,h,0,0,tile.width,tile.height);c.imageSmoothingEnabled=false;c.drawImage(tile,0,0,tile.width,tile.height,x,y,w,h)}}c.restore()}
function render(){if(!image)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0);items.forEach(o=>drawObject(ctx,o));if(selected>=0){const b=bounds(items[selected]),p=5/zoom;ctx.save();ctx.strokeStyle='#2563eb';ctx.lineWidth=1.5/zoom;ctx.setLineDash([5/zoom,4/zoom]);ctx.strokeRect(b.x-p,b.y-p,b.w+2*p,b.h+2*p);ctx.setLineDash([]);ctx.fillStyle='#fff';ctx.fillRect(b.x+b.w-5/zoom,b.y+b.h-5/zoom,10/zoom,10/zoom);ctx.strokeRect(b.x+b.w-5/zoom,b.y+b.h-5/zoom,10/zoom,10/zoom);ctx.restore()}}
function setZoom(v){if(!image)return;zoom=Math.min(4,Math.max(.02,v));canvas.style.width=image.width*zoom+'px';canvas.style.height=image.height*zoom+'px';update();render()}
function fit(){if(!image)return;const board=$('board');setZoom(Math.min(1,(board.clientWidth-72)/image.width,(board.clientHeight-72)/image.height))}
function syncSelected(){const o=items[selected];if(o){$('color').value=o.color;$('width').value=o.width;$('size').value=o.size;if(o.type==='text')$('textInput').value=o.text}update()}
function point(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)/r.width*canvas.width)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)/r.height*canvas.height))}}
function hit(o,p){const b=bounds(o),pad=8/zoom;if(o.type==='arrow'){const length=o.w*o.w+o.h*o.h,t=length?Math.max(0,Math.min(1,((p.x-o.x)*o.w+(p.y-o.y)*o.h)/length)):0;return Math.hypot(p.x-o.x-t*o.w,p.y-o.y-t*o.h)<Math.max(pad,o.width*2)}return p.x>=b.x-pad&&p.x<=b.x+b.w+pad&&p.y>=b.y-pad&&p.y<=b.y+b.h+pad}
canvas.addEventListener('pointerdown',e=>{if(!image||e.button!==0)return;e.preventDefault();canvas.focus();const p=point(e);canvas.setPointerCapture(e.pointerId);if(tool==='select'){if(selected>=0){const b=bounds(items[selected]);if(Math.hypot(p.x-b.x-b.w,p.y-b.y-b.h)<14/zoom){drag={kind:'resize',start:p,original:structuredClone(items[selected]),before:snapshot()};return}}selected=items.findLastIndex(o=>hit(o,p));if(selected>=0){drag={kind:'move',start:p,original:structuredClone(items[selected]),before:snapshot()};syncSelected()}update();render();return}const o={type:tool,x:p.x,y:p.y,w:0,h:0,color:$('color').value,width:+$('width').value,size:+$('size').value};if(tool==='text'){o.text=$('textInput').value.trim();if(!o.text){toast('請先輸入說明文字');return}}if(tool==='number'){o.n=Math.min(999,Math.max(1,parseInt($('nextNumber').value)||1));$('nextNumber').value=Math.min(999,o.n+1)}items.push(o);selected=items.length-1;if(['text','number'].includes(tool)){commit();return}drag={kind:'draw',start:p,before:JSON.stringify(items.slice(0,-1))};update();render()});
canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e),o=items[selected];if(!o)return;if(drag.kind==='draw'){o.w=p.x-drag.start.x;o.h=p.y-drag.start.y}else if(drag.kind==='move'){o.x=drag.original.x+p.x-drag.start.x;o.y=drag.original.y+p.y-drag.start.y}else{const original=drag.original,b=bounds(original);if(['text','number'].includes(o.type)){const ratio=Math.max(.25,(p.x-b.x)/Math.max(1,b.w));o.size=Math.max(16,Math.min(160,Math.round(original.size*ratio)));$('size').value=o.size;update()}else if(o.type==='arrow'){o.w=original.w+p.x-drag.start.x;o.h=original.h+p.y-drag.start.y}else{o.x=b.x;o.y=b.y;o.w=Math.max(4,p.x-b.x);o.h=Math.max(4,p.y-b.y)}}render()});
function finishDrag(){if(!drag)return;if(drag.kind==='draw'){const o=items[selected];if(Math.hypot(o.w,o.h)<5||(['rect','mosaic'].includes(o.type)&&(Math.abs(o.w)<3||Math.abs(o.h)<3))){items.splice(selected,1);selected=-1}}drag=null;commit()}
canvas.addEventListener('pointerup',finishDrag);canvas.addEventListener('lostpointercapture',finishDrag);canvas.addEventListener('pointercancel',()=>{if(drag){items=JSON.parse(drag.before);selected=-1;drag=null;update();render()}});
canvas.addEventListener('dblclick',e=>{if(tool!=='select')return;const i=items.findLastIndex(o=>hit(o,point(e)));if(i>=0&&items[i].type==='text'){selected=i;syncSelected();$('textInput').focus();$('textInput').select();render()}});
function changeStyle(prop,value){if(selected>=0){items[selected][prop]=value;render()}update()}
for(const [id,prop]of [['color','color'],['width','width'],['size','size']]){$(id).addEventListener('input',()=>changeStyle(prop,id==='color'?$(id).value:+$(id).value));$(id).addEventListener('change',commit)}
$('textInput').addEventListener('input',()=>{if(selected>=0&&items[selected].type==='text'){items[selected].text=$('textInput').value;render()}});$('textInput').addEventListener('change',commit);
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{$('color').value=b.dataset.color;changeStyle('color',b.dataset.color);commit()});document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
function removeSelected(){if(selected<0)return;items.splice(selected,1);selected=-1;commit()}
$('delete').onclick=removeSelected;$('undo').onclick=undo;$('redo').onclick=redo;$('fit').onclick=fit;$('zoomIn').onclick=()=>setZoom(zoom*1.25);$('zoomOut').onclick=()=>setZoom(zoom/1.25);
function acceptImage(img,name){if(image&&items.length&&!confirm('開啟新圖片會清除目前標註。請確認已下載需要保留的圖片。'))return;image=img;filename=name.replace(/\.[^.]+$/,'')||'教學截圖';items=[];selected=-1;drag=null;history=['[]'];historyIndex=0;canvas.width=img.width;canvas.height=img.height;$('empty').hidden=true;$('canvasWrap').hidden=false;$('filename').textContent=name;$('dimensions').textContent=img.width+' × '+img.height+' px';$('nextNumber').value=1;setTool('rect');fit();toast('圖片已開啟，拖曳即可新增紅框')}
async function loadFile(file){if(!file)return;if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type)){toast('請選擇 PNG、JPG、WebP 或 GIF 圖片');return}if(file.size>30*1024*1024){toast('請使用 30 MB 以下的圖片');return}const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();if(img.width*img.height>32000000||img.width>16000||img.height>16000)throw new Error('too-large');acceptImage(img,file.name);if(file.type==='image/gif')toast('GIF 會以靜態圖片開啟')}catch(e){toast(e.message==='too-large'?'圖片尺寸過大，請縮小後再開啟':'無法讀取圖片，請換一張再試')}finally{URL.revokeObjectURL(url)}}
$('upload').onclick=$('emptyUpload').onclick=()=>$('file').click();$('file').onchange=e=>{loadFile(e.target.files[0]);e.target.value=''};
document.addEventListener('paste',e=>{const item=[...(e.clipboardData?.items||[])].find(i=>i.type.startsWith('image/'));if(item){e.preventDefault();loadFile(item.getAsFile())}});
let dragDepth=0;document.addEventListener('dragenter',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();dragDepth++;$('dropOverlay').hidden=false}});document.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault()});document.addEventListener('dragleave',()=>{dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)$('dropOverlay').hidden=true});document.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;$('dropOverlay').hidden=true;loadFile(e.dataTransfer.files[0])});
function makeExport(){if(!image)throw new Error('請先開啟圖片');const out=document.createElement('canvas');out.width=image.width;out.height=image.height;const c=out.getContext('2d');c.drawImage(image,0,0);items.forEach(o=>drawObject(c,o));return out}
$('export').onclick=()=>{try{makeExport().toBlob(blob=>{if(!blob){toast('匯出失敗，請再試一次');return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename+'-教學標註.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('已產生 PNG，請查看瀏覽器下載項目')},'image/png')}catch{toast('匯出失敗，請縮小圖片後再試')}};
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||e.target.isContentEditable)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Delete'||e.key==='Backspace'){if(selected>=0){e.preventDefault();removeSelected()}}if(e.key==='Escape'){selected=-1;setTool('select')}const keys={v:'select',r:'rect',a:'arrow',n:'number',t:'text',m:'mosaic'};if(keys[e.key.toLowerCase()])setTool(keys[e.key.toLowerCase()])});
$('demo').onclick=()=>{const d=document.createElement('canvas');d.width=1200;d.height=760;const c=d.getContext('2d');c.fillStyle='#f5f7fb';c.fillRect(0,0,1200,760);c.fillStyle='#22324b';c.fillRect(0,0,1200,76);c.font='bold 26px "Microsoft JhengHei",sans-serif';c.fillStyle='#fff';c.fillText('線上申請系統',38,48);c.font='18px "Microsoft JhengHei",sans-serif';c.fillStyle='#b9c9dd';c.fillText('首頁     我的申請     使用說明',760,46);c.fillStyle='#fff';c.fillRect(50,112,1100,584);c.fillStyle='#24344a';c.font='bold 28px "Microsoft JhengHei",sans-serif';c.fillText('新增活動申請',84,164);c.font='18px "Microsoft JhengHei",sans-serif';c.fillStyle='#66788e';c.fillText('請填寫活動資訊，完成後送出申請。',84,201);const rows=[['活動名稱','校園教學成果分享'],['活動時間','2026 / 10 / 10　09:00 – 12:00'],['活動地點','多功能教室'],['申請人','王小明　｜　example@email.test']];rows.forEach((r,i)=>{const y=242+i*79;c.fillStyle='#4d5b70';c.fillText(r[0],86,y+29);c.fillStyle='#f7f9fc';c.fillRect(230,y,870,50);c.strokeStyle='#dde4ee';c.lineWidth=1;c.strokeRect(230,y,870,50);c.fillStyle='#334155';c.fillText(r[1],250,y+31)});c.fillStyle='#2563eb';c.fillRect(904,591,196,58);c.fillStyle='#fff';c.font='bold 20px "Microsoft JhengHei",sans-serif';c.fillText('送出申請',962,628);c.fillStyle='#8190a3';c.font='16px "Microsoft JhengHei",sans-serif';c.fillText('示範資料 · 可用紅框、編號與文字標出操作順序',86,628);const img=new Image();img.onload=()=>acceptImage(img,'練習截圖.png');img.src=d.toDataURL()};
// Use the same actions and state for supported browser agents.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_annotation_status',title:'讀取標註狀態',description:'Read the currently opened image dimensions and annotation count.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({hasImage:!!image,width:image?.width||0,height:image?.height||0,annotationCount:items.length,tool})})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'set_annotation_tool',title:'選擇標註工具',description:'Select a tool for the next manual annotation. Does not create an annotation.',inputSchema:{type:'object',properties:{tool:{type:'string',enum:Object.keys(hints)}},required:['tool'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||!Object.hasOwn(hints,input.tool))throw new Error('Unknown annotation tool');setTool(input.tool);return{tool}}})).catch(()=>{})}catch{}}
update();
